blueprints/general_routes.py
from flask import Blueprint, current_app, flash, redirect, request, render_template, session, url_for
from sqlalchemy import func
from data import home_page_content, about_page_content, user_dashboard_page_content
from lib.booking_manager import BookingManager
from lib.service_manager import ServiceManager
from lib.donation_manager import DonationManager
from extensions import db
from itsdangerous import URLSafeTimedSerializer, SignatureExpired
from lib.user_manager import UserManager


# Import models
from model import User, Service, Booking, Donation, Charity, Location, Payment

from utils import process_contact_form, is_user_admin

general_blueprint = Blueprint('general_blueprint', __name__)



@general_blueprint.route('/')
def home():
    impact_statistics = home_page_content["social_proof_section"]["impact_statistics"]

    impact_statistics_count =[
        BookingManager.count_past_bookings() + 16_700,
        f"${DonationManager.calculate_total_donations() + 1_150:.2f}",
        max(UserManager.count_users_by_country(), 4)
    ]

    for stats, count in zip(impact_statistics, impact_statistics_count):
        stats['count'] = count

    return render_template(
        'index.html',
        metadata=home_page_content['meta'],
        hero=home_page_content['hero'],
        problem_solution=home_page_content['problem_solution_section'],
        benefits=home_page_content['benefits_section'],
        social_proof=home_page_content["social_proof_section"],
        features=home_page_content["features_section"],
        faq=home_page_content["faq_section"],
        footer=home_page_content['footer']
        )

@general_blueprint.route('/about')
def about():
    return render_template(
        'about.html',
        metadata=about_page_content['meta'],
        content=about_page_content['content'],
        footer=about_page_content['footer']
    )

@general_blueprint.route('/contact', methods=['GET', 'POST'])
def contact():
    if request.method == 'POST':
        name = request.form['name']
        email = request.form['email']
        message = request.form['message']
        
        # Process the contact form data (e.g., send an email, store in database)
        process_contact_form(name, email, message)
        
        return render_template('contact_thankyou.html', name=name, metadata=about_page_content['meta'],
        footer=about_page_content['footer'])

    return render_template(
        'contact.html',
        metadata=about_page_content['meta'],
        footer=about_page_content['footer']
    )

@general_blueprint.route('/services')
def services():
    all_services = ServiceManager.list_all_services()
    return render_template(
        'services.html', 
        metadata=home_page_content['meta'],
        services=all_services,
        footer=about_page_content['footer']
    )

@general_blueprint.route('/user_dashboard')
def user_dashboard():
    user_id = session.get('user_id')
    if not user_id:
        # Redirect to login if user is not logged in
        return redirect(url_for('user_blueprint.login'))

    user_bookings = Booking.query.filter_by(user_id=user_id).all()
    user_donations = Donation.query.filter_by(user_id=user_id).all()
    user_payments = Payment.query.filter_by(user_id=user_id).all()  # Fetch user payments

    user_dashboard_data = {
        'bookings': user_bookings,
        'donations': user_donations,
        'payments': user_payments  # Include payments in the data
    }

    return render_template(
        'user_dashboard.html',
        data=user_dashboard_data,
        metadata=user_dashboard_page_content["meta"], 
        footer=user_dashboard_page_content["footer"]
    )

@general_blueprint.route('/admin_dashboard')
def admin_dashboard():
    if not is_user_admin():
        return "Access denied", 403

    # User-Related Metrics
    user_count = User.query.count()
    users_by_role = db.session.query(User.user_role, func.count(User.id)).group_by(User.user_role).all()
    latest_signups = User.query.order_by(User.create_date.desc()).limit(10).all()

    # Service Metrics
    service_count = Service.query.count()
    services_by_type = db.session.query(Service.service_type, func.count(Service.id)).group_by(Service.service_type).all()
    # Assuming Booking has a relationship with Service as 'service'
    popular_services = db.session.query(Service.name, func.count(Booking.id)).join(Booking).group_by(Service.name).order_by(func.count(Booking.id).desc()).limit(10)

    # Booking Metrics
    booking_count = Booking.query.count()
    monthly_bookings = db.session.query(func.extract('month', Booking.booking_date), func.count(Booking.id)).group_by(func.extract('month', Booking.booking_date)).all()
    bookings_by_status = db.session.query(Booking.status, func.count(Booking.id)).group_by(Booking.status).all()

    # Donation Metrics
    total_donations = Donation.query.with_entities(func.sum(Donation.amount)).scalar()
    donation_count = Donation.query.count()
    avg_donation_amount = db.session.query(func.avg(Donation.amount)).scalar()

    # Location-Based Metrics
    # Assuming Service and Charity have a relationship with Location as 'location'
    services_by_location = db.session.query(Location.city, func.count(Service.id)).join(Service).group_by(Location.city).all()

    # Financial Metrics
    total_payments = db.session.query(func.sum(Payment.amount)).scalar()
    payment_count = Payment.query.count()

    
    formatted_latest_signups = [
        {
            'name': f"{user.first_name} {user.last_name}",
            'signup_date': user.create_date.strftime('%Y-%m-%d'),
            'profile_image': user.profile_image_url,  # Add this if you want to display profile pictures
            'country': user.country
        }
        for user in latest_signups
    ]


    # Set a default value for display when no data is available
    default_display_value = "N/A"

    # Format monetary values as strings
    formatted_total_donations = "${:,.2f}".format(total_donations) if total_donations is not None else default_display_value
    formatted_avg_donation_amount = "${:,.2f}".format(avg_donation_amount)  if avg_donation_amount is not None else default_display_value 
    formatted_users_by_role = {role: count for role, count in users_by_role}
    formatted_services_by_type = {service_type: count for service_type, count in services_by_type}
    popular_services_query = db.session.query(Service.name, func.count(Booking.id)).join(Booking).group_by(Service.name).order_by(func.count(Booking.id).desc()).limit(10)
    popular_services = {service: count for service, count in popular_services_query.all()}
    formatted_bookings_by_status = {status: count for status, count in bookings_by_status}
    month_names = {
        1: "January", 2: "February", 3: "March",
        4: "April", 5: "May", 6: "June",
        7: "July", 8: "August", 9: "September",
        10: "October", 11: "November", 12: "December"
    }
    formatted_monthly_bookings = {month_names.get(month, "Unknown Month"): count for month, count in monthly_bookings}



    admin_dashboard_data = {
        'user_count': user_count,
        'users_by_role': formatted_users_by_role,
        'latest_signups': latest_signups,
        'service_count': service_count,
        'services_by_type': formatted_services_by_type,
        'popular_services': popular_services,
        'booking_count': booking_count,
        'monthly_bookings': formatted_monthly_bookings,
        'bookings_by_status': formatted_bookings_by_status,
        'total_donations': formatted_total_donations,
        'donation_count': donation_count,
        'avg_donation_amount': formatted_avg_donation_amount,
        'services_by_location': services_by_location,
        'total_payments': total_payments,
        'payment_count': payment_count
    }
    print(admin_dashboard_data)

    return render_template('admin_dashboard.html', data=admin_dashboard_data, metadata=user_dashboard_page_content["meta"], 
        footer=user_dashboard_page_content["footer"])

@general_blueprint.route('/confirm/<token>')
def confirm_email(token):
    try:
        serializer = URLSafeTimedSerializer(current_app.config['SECRET_KEY'])
        email = serializer.loads(
            token,
            salt=current_app.config['SECURITY_PASSWORD_SALT'],
            max_age=3600
        )
    except SignatureExpired:
        flash('The confirmation link has expired.', 'error')
        return redirect(url_for('user_blueprint.login'))

    user = UserManager.get_user_by_email(email)
    if user and not user.confirmed:
        UserManager.update_user(user.id, confirmed=True)  # Correctly pass user ID and confirmed field
        flash('Your email has been confirmed.', 'success')
    else:
        flash('Invalid or already confirmed token.', 'error')

    return redirect(url_for('user_blueprint.login'))

blueprints/user_routes.py
import uuid
from flask import current_app
from flask import Blueprint, redirect, request, render_template, session, flash, url_for
from werkzeug.utils import secure_filename

from itsdangerous import SignatureExpired, URLSafeTimedSerializer
from lib.location_manager import LocationManager
# from flask import Flask, request

from lib.user_manager import UserManager

from data import home_page_content, about_page_content, login_page_content, register_page_content, profile_page_content

from werkzeug.security import generate_password_hash

from utils import send_email, send_username_recovery_email

user_blueprint = Blueprint('user_blueprint', __name__)

@user_blueprint.route('/register', methods=['GET', 'POST'])
def register_user():
    if request.method == 'POST':
        # Process the registration form
        data = request.form
        email = data['email']

        # Check if a user with this email already exists
        existing_user = UserManager.get_user_by_email(email)
        if existing_user:
            flash('An account with this email already exists.', 'error')
            return redirect(url_for('user_blueprint.register_user'))

        # Continue with the user creation process
        country_code = data.get('country')
        new_user = UserManager.add_user(
            username=data['username'].lower(),
            email=email,
            password=data['password'],
            first_name=data.get('first_name', ''),
            last_name=data.get('last_name', ''),
            country=country_code
        )

        # Generate a token for email confirmation
        serializer = URLSafeTimedSerializer(current_app.config['SECRET_KEY'])
        token = serializer.dumps(new_user.email, salt=current_app.config['SECURITY_PASSWORD_SALT'])

        # Construct the confirm URL
        confirm_url = url_for('general_blueprint.confirm_email', token=token, _external=True)

        # Send the confirmation email
        html = render_template('email/activate.html', confirm_url=confirm_url)
        send_email(new_user.email, 'Confirm Your Email', html)

        flash('A confirmation email has been sent to your email address.', 'info')
        return redirect(url_for('user_blueprint.login'))

    # Display the registration form for GET request
    return render_template(
        'register.html', 
        metadata=register_page_content["meta"], 
        footer=register_page_content["footer"]
    )

@user_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form['username'].lower()
        password = request.form['password']
        user = UserManager.get_user_by_username(username)

        if user:
            if not user.confirmed:
                flash('Please confirm your email address before logging in.', 'warning')
                return redirect(url_for('user_blueprint.login'))

            if UserManager.check_password(user.id, password):
                session['user_id'] = user.id  # User is logged in
                return redirect(url_for('user_blueprint.profile'))
            else:
                flash('Invalid username or password', 'error')
        else:
            flash('Invalid username or password', 'error')

    return render_template(
        'login.html',
        metadata=login_page_content["meta"], 
        footer=login_page_content["footer"]
    )

@user_blueprint.route('/logout')
def logout():
    session.pop('user_id', None)  # User is logged out
    return redirect(url_for('user_blueprint.login'))

@user_blueprint.route('/profile', methods=['GET', 'POST'])
def profile():
    user_id = session.get('user_id')
    if not user_id:
        return redirect(url_for('user_blueprint.login'))

    user = UserManager.get_user_by_id(user_id)
    if request.method == 'POST':
        user_data = {
            'first_name': request.form.get('first_name'),
            'last_name': request.form.get('last_name'),
            'bio': request.form.get('bio'),
            'country': request.form.get('country'),
        }

        # Handle profile image upload
        profile_image = request.files.get('profile_image')
        if profile_image:
            folder_name = 'profile_images/'  # Specify the folder name
            bucket_name = 'prophet-yani-assests'  # Replace with your actual bucket name

            # Generate a unique file name
            filename = secure_filename(profile_image.filename)
            unique_filename = str(uuid.uuid4()) + "_" + filename

            # Combine folder name and unique filename to create the S3 object key
            s3_object_key = folder_name + unique_filename

            image_url = UserManager.upload_to_s3(profile_image, bucket_name, s3_object_key)
            if image_url:
                # Update user with new profile image URL
                user_data['profile_image_url'] = image_url
                # Update user in the database
                UserManager.update_user(user_id, user_data)


        # Check and update password if new_password field is provided
        new_password = request.form.get('new_password')
        if new_password:
            UserManager.update_password(user_id, new_password)
            flash('Your password has been updated.', 'success')

        # Refresh user data after updates
        user = UserManager.get_user_by_id(user_id)

        flash('Profile updated successfully.', 'success')

    return render_template(
        'profile.html', 
        metadata=profile_page_content["meta"],
        footer=profile_page_content["footer"],
        user=user
    )

@user_blueprint.route('/password_reset', methods=['GET', 'POST'])
def password_reset():
    if request.method == 'POST':
        email = request.form['email']
        user = UserManager.get_user_by_email(email)
        if user:
            # Generate a token for password reset
            serializer = URLSafeTimedSerializer(current_app.config['SECRET_KEY'])
            token = serializer.dumps(email, salt=current_app.config['SECURITY_PASSWORD_SALT'])

            # Construct the password reset URL
            reset_url = url_for('user_blueprint.reset_password_token', token=token, _external=True)

            # Send the password reset email
            html = render_template('email/reset_password.html', reset_url=reset_url)
            send_email(email, 'Password Reset Request', html)

            flash('A password reset email has been sent.', 'info')
        else:
            flash('Email not found', 'error')

    return render_template('password_reset.html',
                           metadata=profile_page_content["meta"],
                            footer=profile_page_content["footer"]
                            )

@user_blueprint.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_password_token(token):
    try:
        serializer = URLSafeTimedSerializer(current_app.config['SECRET_KEY'])
        email = serializer.loads(
            token,
            salt=current_app.config['SECURITY_PASSWORD_SALT'],
            max_age=3600
        )
    except SignatureExpired:
        flash('The password reset link has expired.', 'error')
        return redirect(url_for('user_blueprint.password_reset'))

    user = UserManager.get_user_by_email(email)
    if user is None:
        flash('Invalid password reset token.', 'error')
        return redirect(url_for('user_blueprint.login'))

    if request.method == 'POST':
        new_password = request.form['password']
        # Ensure password hashing
        hashed_password = generate_password_hash(new_password)
        UserManager.update_password(user.id, new_password)
        flash('Your password has been updated.', 'success')
        return redirect(url_for('user_blueprint.login'))

    return render_template('reset_password_with_token.html', token=token)

@user_blueprint.route('/recover_username', methods=['GET', 'POST'])
def recover_username():
    if request.method == 'POST':
        email = request.form['email']
        user = UserManager.get_user_by_email(email)
        if user:
            # Send an email with the username
            send_username_recovery_email(user.email, user.username)
            flash('A recovery email with your username has been sent.', 'info')
        else:
            flash('No account found with that email.', 'error')
    return render_template('recover_username.html',
                           metadata=profile_page_content["meta"],
                           footer=profile_page_content["footer"])

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ metadata.page_title }}</title>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap" rel="stylesheet">
    <link href="https://db.onlinewebfonts.com/c/45efcf93d0c9504aa316c9bb7ce66a2e?family=Pietra+LP+W01+Regular" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="icon" type="image/webp" href="https://jonathanksullivan.github.io/prophet-yani/image/logo.webp">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/main.css') }}">
    {% block head %}
    {% endblock %}
</head>
<body>
    <header class="text-center">
        <!-- Navbar -->
    {% include "base/navbar.html" %}

        <!-- This can be a common header or you can use Jinja's block to make it customizable -->
        {% block header %}
        <!-- Unique Page header will go here -->
        {% endblock %}
    </header>

    <main>
        {% block content %}
        <!-- Unique Page Content will go here -->
        {% endblock %}
    </main>

    <footer class="text-center mt-5">
        <p>{{ footer.text | safe }}</p>
    </footer>

    <script>
        // JavaScript to add the 'opaque' class to the navbar on scroll
        window.addEventListener('scroll', function() {
            var navbar = document.querySelector('.navbar');
            if (window.scrollY > 50) { // Adjust the scroll threshold as needed
                navbar.classList.add('opaque');
            } else {
                navbar.classList.remove('opaque');
            }
        });

    </script>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

templates/community_coming_soon.html
{% extends "base.html" %}  <!-- Replace with your actual base template file name -->
{% block head %}
<!-- Any additional head content specific to the community page -->
<style>
    .header-section {
        background: url("{{ url_for('static', filename='images/community_coming_soon.webp') }}") no-repeat center center;
        background-size: cover;
        height: 100vh; /* Make header take up the full viewport height */
        text-align: center;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        color: white;
    }
   .feature-item {
    background-color: #f8f9fa;
    border-radius: 10px;
    padding: 20px;
    margin-bottom: 15px;
   }
   .feature-icon {
    font-size: 24px;
    color: #800080; /* Dark purple color */
   }
   .join-btn {
    background-color: #800080; /* Dark purple color */
    color: white;
    border-radius: 5px;
    padding: 10px 20px;
    text-decoration: none;
    display:
    inline-block;
   }
   .join-btn:hover {
    background-color: #660066; /* Slightly darker purple */
    color: #FFF; /* Slightly darker purple */
   }
</style>
{% endblock %}
{% block header %}
<header class="header-section">
    <div class="container text-center">
        <h1 class="display-4">Our Community</h1>
        <p class="lead">Exciting Community Features on Their Way</p>
    </div>
</header>
{% endblock %}
{% block content %}
<div class="container py-5">
<div class="row justify-content-center">
   <div class="col-lg-10">
      <p class="lead text-center mb-4">We're crafting a dynamic community space full of enriching features to connect, share, and grow. Get ready for:</p>
      <div class="row">
         <div class="col-md-6 mb-3">
            <div class="feature-item">
               
               <h4><i class="fas fa-calendar-alt feature-icon"></i> Exclusive Events</h4>
               <p>Interactive workshops, seminars, and gatherings tailored to foster learning and connection.</p>
            </div>
         </div>
         <div class="col-md-6 mb-3">
            <div class="feature-item">
               <h4><i class="fas fa-comments feature-icon"></i> Engaging Forums</h4>
               <p>Join insightful discussions, share unique experiences, and form bonds with peers globally.</p>
            </div>
         </div>
         <div class="col-md-6 mb-3">
            <div class="feature-item">
               <h4><i class="fas fa-users feature-icon"></i> Dedicated Discord Servers</h4>
               <p>A real-time platform for instant communication, community building, and collaborative experiences.</p>
            </div>
         </div>
         <div class="col-md-6 mb-3">
            <div class="feature-item">
               <h4><i class="fas fa-video feature-icon"></i> Live Stream Conference Rooms</h4>
               <p>Virtual live streaming sessions for more interactive and engaging online conferences and meetups.</p>
            </div>
         </div>
      </div>
      <div class="text-center mt-5">
         <h3>Perpetual Google Meet Room</h3>
         <p>Join our ever-open Google Meet room for real-time interactions and discussions with community members and leaders.</p>
         <a href="https://meet.google.com/jdo-jhqo-nva" class="join-btn mt-3" target="_blank">Join Google Meet</a>
      </div>
   </div>
</div>
{% endblock %}

templates/contact.html
{% extends "base.html" %}

{% block head %}
<style>
    /* Custom CSS for header */
    .header-section {
        background: url("https://jonathanksullivan.github.io/prophet-yani/image/contact_hero.webp") no-repeat center center;
        background-size: cover;
        height: 100vh; /* Make header take up the full viewport height */
        text-align: center;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        color: white;
    }
</style>
{% endblock %}

{% block header %}
<header class="header-section">
    <div class="container text-center">
        <h1 class="display-4">Contact Us</h1>
        <p class="lead">We're here to help and answer any questions you might have</p>
    </div>
</header>
{% endblock %}

{% block content %}
<div class="container py-5">
    <div class="row">
        <div class="col-lg-8 mx-auto">
            <h2 class="text-center mb-4">We'd love to hear from you</h2>
            <form action="{{ url_for('general_blueprint.contact') }}" method="post">
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="Enter your name" required>
                </div>
                <div class="form-group">
                    <label for="email">Email address</label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="Enter your email" required>
                </div>
                <div class="form-group">
                    <label for="message">Message</label>
                    <textarea class="form-control" id="message" name="message" rows="4" required></textarea>
                </div>
                <button type="submit" class="btn btn-primary btn-block">Submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/contact_thankyou.html
{% extends "base.html" %}

{% block head %}
<style>
    /* Custom CSS for header */
    .header-section {
        background: url({{ url_for('static', filename='images/contact_thanks.webp') }}) no-repeat center center;
        background-size: cover;
        height: 100vh; /* Make header take up the full viewport height */
        text-align: center;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        color: white;
    }
</style>
{% endblock %}

{% block header %}
<header class="header-section">
    <div class="container text-center">
    </div>
</header>
    
{% endblock %}

{% block content %}
    <div class="container mt-4 text-center">
        <h2>Thanks for Reaching Out, {{ name }}!</h2>
        <p>Your message has been successfully sent. We will get back to you as soon as possible.</p>
        <a href="{{ url_for('general_blueprint.home') }}" class="btn btn-primary">Return to Home</a>
    </div>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block head %}
   <style>
      #subtitle {
        margin: 20px 0 30px 0;
      }
      .feature-card-title {
         font-weight: 400;
         font-size: 21px;
      }
      .benefit-link {
         color: darkpurple; /* Replace with your preferred shade of dark purple */
         text-decoration: underline; /* Removes the default underline */
         border-bottom: 2px solid darkpurple; /* Adds a flat underline */
         padding-bottom: 2px; /* Adjusts the space between the text and the underline */
         transition: border-color 0.3s; /* Smooth transition for hover effect */
      }

      .benefit-link:hover, .benefit-link:focus {
         border-bottom-color: lighten(darkpurple, 10%); /* Lightens the underline on hover/focus */
      }
      .home-social-number {
         font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
      }
   </style>
{% endblock %}


{% block header %}
   <!-- Hero Section -->
   {% include "home/hero_section.html" %}
{% endblock %}

{% block content %}
   <!-- Problem/Solution Section -->
   {% include "home/problem_solution_section.html" %}

   <!-- Benefits Section -->
   {% include "home/benefits_section.html" %}

   <!-- Social Proof Section -->
   {% include "home/social_proof_section.html" %}

   <!-- Call to Action Section -->
   {% include "home/cta_section.html" %}
   
   <!-- Feature Section -->
   {% include "home/feature_section.html" %}

   <!-- FAQ Section -->
   {% include "home/faq_section.html" %}

   <!-- Call to Action Section -->
   {% include "home/cta_section.html" %}
   
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h2 class="mb-4 text-center">Login</h2>
            <!-- Display any flash messages here -->
            {% with messages = get_flashed_messages() %}
              {% if messages %}
                <div class="alert alert-warning">
                  {% for message in messages %}
                    {{ message }}
                  {% endfor %}
                </div>
              {% endif %}
            {% endwith %}
            <form method="POST" action="{{ url_for('user_blueprint.login') }}">
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" class="form-control" id="username" name="username" required>
                </div>
                <!-- Password Field with Visibility Toggle -->
                <div class="form-group">
                  <label for="password">Password</label>
                  <div class="input-group">
                      <input type="password" class="form-control" id="password" name="password" required>
                      <div class="input-group-append">
                          <button class="btn btn-outline-secondary" type="button" id="togglePassword">
                              <i class="fas fa-eye"></i>
                          </button>
                      </div>
                  </div>
                </div>

                <button type="submit" class="btn btn-primary">Log In</button>
            </form>
            <div class="mt-3">
                <a href="{{ url_for('user_blueprint.password_reset') }}">Forgot password?</a>
                <br>
                <a href="{{ url_for('user_blueprint.recover_username') }}">Forgot username?</a>
                <br>
                <a href="{{ url_for('user_blueprint.register_user') }}">Don't have an account? Register</a>
            </div>
          
        </div>
    </div>
</div>

<script>
  // Toggle Password Visibility
document.getElementById('togglePassword').addEventListener('click', function (e) {
    // Prevent the button from submitting the form
    e.preventDefault();

    // Toggle the type attribute
    const passwordInput = document.getElementById('password');
    const type = passwordInput.getAttribute('type') === 'password' ? 'text' : 'password';
    passwordInput.setAttribute('type', type);

    // Toggle the eye / eye-slash icon
    this.innerHTML = type === 'password' ? '<i class="fas fa-eye"></i>' : '<i class="fas fa-eye-slash"></i>';
});

</script>
{% endblock %}

templates/recover_username.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h2 class="mb-4 text-center">Recover Username</h2>
            <!-- Display flash messages here -->
            {% with messages = get_flashed_messages() %}
            {% if messages %}
                <div class="alert alert-warning">
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
                </div>
            {% endif %}
            {% endwith %}
            <form method="POST" action="{{ url_for('user_blueprint.recover_username') }}">
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" class="form-control" id="email" name="email" required>
                </div>
                <button type="submit" class="btn btn-primary">Recover Username</button>
            </form>
            <div class="mt-3">
                <a href="{{ url_for('user_blueprint.login') }}">Back to Login</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}